#!/usr/bin/env python3
"""
Generate sql/nf_live.sql — the New Frontiers keep / component / position /
hookpoint / teleport data, sourced from the Eve-of-Darkness vanilla DOL
database (https://github.com/Eve-of-Darkness/db-public).

Why this exists
---------------
OpenDAoC-SinglePlayerBots' code targets New Frontiers (region 163) — see
KeepManager.DEFAULT_FRONTIERS_REGION and GetBorderKeepLocation — but the
upstream OpenDAoC-Database ships keeps only in the Old Frontier regions
(1 Albion, 100 Midgard, 200 Hibernia) and an empty keepcomponent table.
This generator fetches the canonical NF data from the EoD repository and
emits an idempotent SQL patch the entrypoint applies on every server boot.

What it emits
-------------
  1. UPDATE 21 main NF keeps (KeepID 50–56 / 75–81 / 100–106) — region 163,
     EoD-canonical coordinates, replacing the OF rows shipped upstream.
  2. UPDATE 6 relic keeps to region 163, using approximate NF coordinates
     placed inside the canonical relic-keep zone for each realm
     (Pennine Mountains / Yggdra Forest / Mount Collory).
  3. REPLACE INTO ~85 NF tower keep rows (KeepID 306+) absent from upstream.
  4. REPLACE INTO ~960 NF keep components — both OF-skin (<20) and NF-skin
     (>20) sets so USE_NEW_KEEPS=0 and =1 both render visible structures.
  5. REPLACE INTO ~730 KeepHookPoint template rows (skin-keyed, region-
     independent) — required for guard placement on every keep skin.
  6. REPLACE INTO ~260 KeepPosition template rows — guard / door / patrol
     templates referenced by every keep at runtime.
  7. UPDATE 6 Teleport rows for the realm-master border destinations
     (Castle Sauvage / Snowdonia / Svasud / Vindsaul / Druim Ligen /
     Druim Cain) → region 163 with the canonical coords already hard-
     coded in KeepManager.GetBorderKeepLocation.
  8. UPDATE serverproperty use_new_keeps → 1 so the NF appearance is loaded.

Inputs are fetched once into a /build cache during the docker build step
(see Dockerfile). The output SQL uses REPLACE INTO + UPDATE everywhere so
it is safe to apply on every container start without doubling rows.

Run manually:
    python3 scripts/build_nf_live_sql.py <eod-db-checkout> <output-sql-path>
where <eod-db-checkout> contains data/Keep.json etc.
"""
import json
import os
import sys
from datetime import datetime


def sql_str(s):
    """Quote a Python string for MariaDB."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def sql_int(v):
    return 'NULL' if v is None else str(int(v))


HEADER = """-- =====================================================================
-- NF Live - New Frontiers keep / component / position / hookpoint data
-- =====================================================================
-- AUTO-GENERATED by scripts/build_nf_live_sql.py from the Eve-of-Darkness
-- vanilla DOL database (data/Keep.json, KeepComponent.json, KeepPosition.json,
-- KeepHookPoint.json). Do NOT edit by hand — rerun the generator instead.
--
-- The OpenDAoC-Database upstream ships frontier keeps in regions 1/100/200
-- (Old Frontiers) and an empty keepcomponent table. KeepManager in this
-- fork targets region 163 (New Frontiers — see DEFAULT_FRONTIERS_REGION),
-- so without this patch the frontier loads as terrain only: no keeps, no
-- towers, no visible structures, and the realm-master teleporters drop the
-- player in an empty Old Frontier instead of NF.
--
-- This patch is idempotent (REPLACE INTO + UPDATE) and applied by the
-- gameserver entrypoint on every container start, the same way as
-- heretic_live.sql and battlegrounds_live.sql.
-- =====================================================================
SET FOREIGN_KEY_CHECKS = 0;

"""

FOOTER = """
-- ---- Server property: USE_NEW_KEEPS = 1 (NF appearance) -----------
-- KeepManager.Load filters keep components by Skin: <20 for OF look,
-- >20 for NF look. The default upstream is 0; flip it so the freshly
-- inserted NF rows render with the NF appearance set.
UPDATE `serverproperty` SET Value = '1'
 WHERE `Key` = 'use_new_keeps' AND Value = '0';

SET FOREIGN_KEY_CHECKS = 1;
-- =====================================================================
-- End nf_live.sql
-- =====================================================================
"""


# Approximate NF coordinates for the 6 relic keeps. The EoD dump only carries
# the 21 main keeps + 84 towers — relic-keep rows live in the current OF
# data and need NF-region replacements. Coords are picked inside the
# canonical relic-keep zones for each realm so they sit on solid terrain:
#   Albion relics → Pennine Mountains (zone 177, X∈[557056,622592] Y∈[557056,622592])
#   Midgard relics → Yggdra Forest    (zone 169, X∈[655360,720896] Y∈[360448,425984])
#   Hibernia relics → Mount Collory   (zone 174, X∈[425984,491520] Y∈[622592,688128])
RELIC_KEEPS = [
    # (KeepID, Realm, X, Y, Z, Heading, Name)
    ( 57, 1, 590000, 590000, 8500, 1920, 'Castle Excalibur'),
    ( 58, 1, 605000, 605000, 8500, 3645, 'Castle Myrddin'),
    ( 82, 2, 680000, 380000, 8500, 2977, 'Grallarhorn Faste'),
    (198, 2, 700000, 410000, 8500,  470, 'Mjollner Faste'),
    (110, 3, 460000, 640000, 8500, 2474, 'Dun Dagda'),
    (111, 3, 455000, 660000, 8500, 3925, 'Dun Lamfhota'),
]

# Border-keep teleport destinations — KeepManager.GetBorderKeepLocation has the
# canonical NF coords; we mirror them into Teleport rows so the realm masters
# (Master Visur / Stor Gothi Annark / Channeler Glasny) land players inside
# NF instead of the empty OF border zones.
BORDER_TELEPORTS = [
    # (TeleportID, Realm, X, Y, Z, Heading)
    ('Castle Sauvage',     1, 653811, 616998, 9560, 2040),
    ('Snowdonia Fortress', 1, 616149, 679042, 9560, 1611),
    ('Svasud Faste',       2, 651460, 313758, 9432, 1004),
    ('Vindsaul Faste',     2, 715179, 365101, 9432,  314),
    ('Druim Ligen',        3, 396519, 618017, 9838, 2159),
    ('Druim Cain',         3, 432841, 680032, 9747, 2585),
]


def emit_keeps(out, keeps):
    """Emit UPDATE / REPLACE for each NF keep row."""
    out.write("-- ---- NF main keeps (21) + NF towers (84) --------------------------\n")
    out.write("-- Sourced from Eve-of-Darkness Keep.json, region 163.\n\n")
    out.write("REPLACE INTO `keep` "
              "(`KeepID`,`Name`,`Region`,`X`,`Y`,`Z`,`Heading`,`Realm`,`Level`,"
              "`ClaimedGuildName`,`AlbionDifficultyLevel`,`MidgardDifficultyLevel`,"
              "`HiberniaDifficultyLevel`,`OriginalRealm`,`KeepType`,`BaseLevel`,"
              "`SkinType`,`CreateInfo`,`LastTimeRowUpdated`,`Keep_ID`) VALUES\n")
    rows = []
    for k in sorted(keeps, key=lambda x: x['KeepID']):
        if k['Region'] != 163:
            continue
        rows.append(
            f"  ({k['KeepID']}, {sql_str(k['Name'])}, 163, {k['X']}, {k['Y']}, {k['Z']}, "
            f"{k['Heading']}, {k['Realm']}, {k['Level']}, {sql_str(k.get('ClaimedGuildName'))}, "
            f"{k['AlbionDifficultyLevel']}, {k['MidgardDifficultyLevel']}, "
            f"{k['HiberniaDifficultyLevel']}, {k['OriginalRealm']}, {k['KeepType']}, "
            f"{k['BaseLevel']}, {k['SkinType']}, {sql_str(k.get('CreateInfo', ''))}, "
            f"{sql_str(k['LastTimeRowUpdated'])}, {sql_str(k['Keep_ID'])})"
        )
    out.write(",\n".join(rows))
    out.write(";\n\n")


def emit_relic_keeps(out):
    """Move the 6 relic keeps from OF to NF with reasonable NF coords."""
    out.write("-- ---- Relic keeps (6) — moved from OF to NF -------------------------\n")
    out.write("-- Coordinates are approximate (no canonical NF relic-keep coords in\n")
    out.write("-- the EoD vanilla dump). Placed inside the canonical NF relic zone\n")
    out.write("-- for each realm. Adjust in-place if you want pixel-perfect retail\n")
    out.write("-- positioning — the keeps will work either way.\n\n")
    for kid, realm, x, y, z, heading, name in RELIC_KEEPS:
        out.write(f"UPDATE `keep` SET Region = 163, X = {x}, Y = {y}, Z = {z}, "
                  f"Heading = {heading}\n WHERE KeepID = {kid};\n")
    out.write("\n")


def emit_components(out, comps, nf_keep_ids):
    """Emit components for the NF keep set."""
    out.write("-- ---- Keep components (~960 rows for NF main keeps + towers) -------\n")
    out.write("-- Both Skin<20 (OF appearance) and Skin>20 (NF appearance) variants\n")
    out.write("-- are included. KeepManager filters by USE_NEW_KEEPS at load time.\n\n")
    out.write("REPLACE INTO `keepcomponent` "
              "(`X`,`Y`,`Heading`,`Health`,`Skin`,`KeepID`,`ID`,`CreateInfo`,"
              "`LastTimeRowUpdated`,`KeepComponent_ID`) VALUES\n")
    rows = []
    for c in comps:
        if c['KeepID'] not in nf_keep_ids:
            continue
        rows.append(
            f"  ({c['X']}, {c['Y']}, {c['Heading']}, {c['Health']}, {c['Skin']}, "
            f"{c['KeepID']}, {c['ID']}, {sql_str(c.get('CreateInfo', ''))}, "
            f"{sql_str(c['LastTimeRowUpdated'])}, {sql_str(c['KeepComponent_ID'])})"
        )
    # Chunk to keep statements at ~500 rows each — MariaDB max_allowed_packet
    # default is 16MB; chunking also makes parse errors easier to locate.
    CHUNK = 500
    for i in range(0, len(rows), CHUNK):
        if i > 0:
            out.write(";\n\nREPLACE INTO `keepcomponent` "
                      "(`X`,`Y`,`Heading`,`Health`,`Skin`,`KeepID`,`ID`,`CreateInfo`,"
                      "`LastTimeRowUpdated`,`KeepComponent_ID`) VALUES\n")
        out.write(",\n".join(rows[i:i+CHUNK]))
    out.write(";\n\n")


def emit_hookpoints(out, hps):
    out.write("-- ---- Keep hook-point templates (skin-keyed, region-independent) ----\n")
    out.write("-- Required so the keep manager can place guards / doors on every skin.\n\n")
    out.write("REPLACE INTO `keephookpoint` "
              "(`HookPointID`,`KeepComponentSkinID`,`X`,`Y`,`Z`,`Heading`,`Height`,"
              "`LastTimeRowUpdated`,`KeepHookPoint_ID`) VALUES\n")
    rows = []
    for h in hps:
        rows.append(
            f"  ({h['HookPointID']}, {h['KeepComponentSkinID']}, {h['X']}, {h['Y']}, "
            f"{h['Z']}, {h['Heading']}, {h['Height']}, "
            f"{sql_str(h['LastTimeRowUpdated'])}, {sql_str(h['KeepHookPoint_ID'])})"
        )
    CHUNK = 500
    for i in range(0, len(rows), CHUNK):
        if i > 0:
            out.write(";\n\nREPLACE INTO `keephookpoint` "
                      "(`HookPointID`,`KeepComponentSkinID`,`X`,`Y`,`Z`,`Heading`,`Height`,"
                      "`LastTimeRowUpdated`,`KeepHookPoint_ID`) VALUES\n")
        out.write(",\n".join(rows[i:i+CHUNK]))
    out.write(";\n\n")


def emit_positions(out, positions):
    out.write("-- ---- Keep position templates (guard / door spawns per skin) ---------\n\n")
    out.write("REPLACE INTO `keepposition` "
              "(`ComponentSkin`,`ComponentRotation`,`TemplateID`,`Height`,`XOff`,`YOff`,"
              "`ZOff`,`HOff`,`ClassType`,`TemplateType`,`KeepType`,`LastTimeRowUpdated`,"
              "`KeepPosition_ID`) VALUES\n")
    rows = []
    for p in positions:
        rows.append(
            f"  ({p['ComponentSkin']}, {p['ComponentRotation']}, {sql_str(p['TemplateID'])}, "
            f"{p['Height']}, {p['XOff']}, {p['YOff']}, {p['ZOff']}, {p['HOff']}, "
            f"{sql_str(p.get('ClassType'))}, {p['TemplateType']}, {p['KeepType']}, "
            f"{sql_str(p['LastTimeRowUpdated'])}, {sql_str(p['KeepPosition_ID'])})"
        )
    CHUNK = 500
    for i in range(0, len(rows), CHUNK):
        if i > 0:
            out.write(";\n\nREPLACE INTO `keepposition` "
                      "(`ComponentSkin`,`ComponentRotation`,`TemplateID`,`Height`,`XOff`,`YOff`,"
                      "`ZOff`,`HOff`,`ClassType`,`TemplateType`,`KeepType`,`LastTimeRowUpdated`,"
                      "`KeepPosition_ID`) VALUES\n")
        out.write(",\n".join(rows[i:i+CHUNK]))
    out.write(";\n\n")


def emit_teleports(out):
    out.write("-- ---- Border-keep teleport destinations → NF region 163 -------------\n")
    out.write("-- Coords match KeepManager.GetBorderKeepLocation. Without this UPDATE\n")
    out.write("-- the realm-master 'Castle Sauvage' / 'Snowdonia' / ... destinations\n")
    out.write("-- still point to the now-empty Old Frontier regions 1/100/200.\n\n")
    for tid, realm, x, y, z, heading in BORDER_TELEPORTS:
        # The Atlas teleport row IDs follow a known naming scheme — match either
        # the upstream Type='' rows or the 'Emissary' variants.
        out.write(f"UPDATE `teleport` SET RegionID = 163, X = {x}, Y = {y}, "
                  f"Z = {z}, Heading = {heading}\n"
                  f" WHERE TeleportID = {sql_str(tid)} AND Realm = {realm};\n")
    out.write("\n")


def emit_region_frontier_flags(out):
    out.write("-- ---- Region frontier flags ----------------------------------------\n")
    out.write("-- Without these flips, KeepManager.Load reads IsFrontier from the DB\n")
    out.write("-- and builds m_frontierRegionsList = {1, 100, 200} (the upstream OF\n")
    out.write("-- defaults), excluding 163. GetKeepsByRealmMap then silently filters\n")
    out.write("-- out every NF keep -> the warmap has no colored ownership markers\n")
    out.write("-- and the realm-master 'teleport to keep' path refuses to fire.\n")
    out.write("-- Apply BEFORE inserting keeps so the manager builds the right list\n")
    out.write("-- at first boot (and idempotent on re-boots).\n\n")
    out.write("UPDATE `regions` SET IsFrontier = 1 WHERE RegionID = 163;\n")
    out.write("UPDATE `regions` SET IsFrontier = 0 WHERE RegionID IN (1, 100, 200);\n\n")


def main():
    if len(sys.argv) < 3:
        sys.stderr.write("usage: build_nf_live_sql.py <eod-db-checkout> <output-sql>\n")
        sys.exit(2)
    eod = sys.argv[1]
    outpath = sys.argv[2]

    keeps = json.load(open(os.path.join(eod, 'data', 'Keep.json')))
    comps = json.load(open(os.path.join(eod, 'data', 'KeepComponent.json')))
    hps   = json.load(open(os.path.join(eod, 'data', 'KeepHookPoint.json')))
    poss  = json.load(open(os.path.join(eod, 'data', 'KeepPosition.json')))

    nf_keeps = [k for k in keeps if k['Region'] == 163]
    nf_keep_ids = {k['KeepID'] for k in nf_keeps}

    os.makedirs(os.path.dirname(outpath) or '.', exist_ok=True)
    with open(outpath, 'w', encoding='utf-8', newline='\n') as out:
        out.write(HEADER)
        emit_region_frontier_flags(out)
        emit_keeps(out, nf_keeps)
        emit_relic_keeps(out)
        emit_components(out, comps, nf_keep_ids)
        emit_hookpoints(out, hps)
        emit_positions(out, poss)
        emit_teleports(out)
        out.write(FOOTER)

    sz = os.path.getsize(outpath)
    sys.stderr.write(
        f"nf_live.sql: {sz/1024:.0f} KB | "
        f"{len(nf_keeps)} keeps, {sum(1 for c in comps if c['KeepID'] in nf_keep_ids)} components, "
        f"{len(hps)} hookpoints, {len(poss)} positions, "
        f"{len(BORDER_TELEPORTS)} teleports, {len(RELIC_KEEPS)} relic-keeps moved\n"
    )


if __name__ == '__main__':
    main()
